version: '{build}'
image: Ubuntu
stack: docker
configuration: Release
init: |
  if [ -e "/usr/local/bin/docker-compose" ]; then
    exit 0
  fi
  curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  chmod +x docker-compose
  sudo mv docker-compose /usr/local/bin
cache:
  - /usr/local/bin -> .appveyor.yml
build:
  verbosity: minimal
test_script:
- sh: |
    dotnet test test/Kongverge.Tests/Kongverge.Tests.csproj
    docker-compose -f test/Kongverge.IntegrationTests/docker-compose.yml up --no-start
    dotnet test test/Kongverge.IntegrationTests/Kongverge.IntegrationTests.csproj
    docker-compose -f test/Kongverge.IntegrationTests/docker-compose.yml down
artifacts:
- path: '**\*.nupkg'
deploy: off